In [22]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/playground-series-s6e3/sample_submission.csv
/kaggle/input/competitions/playground-series-s6e3/train.csv
/kaggle/input/competitions/playground-series-s6e3/test.csv

In [23]:
train_df = pd.read_csv('/kaggle/input/competitions/playground-series-s6e3/train.csv')
train_df.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

In [24]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                594194 non-null  int64
 1   gender            594194 non-null  object
 2   SeniorCitizen     594194 non-null  int64
 3   Partner           594194 non-null  object
 4   Dependents        594194 non-null  object
 5   tenure            594194 non-null  int64
 6   PhoneService      594194 non-null  object
 7   MultipleLines     594194 non-null  object
 8   InternetService   594194 non-null  object
 9   OnlineSecurity    594194 non-null  object
 10  OnlineBackup      594194 non-null  object
 11  DeviceProtection  594194 non-null  object
 12  TechSupport       594194 non-null  object
 13  StreamingTV       594194 non-null  object
 14  StreamingMovies   594194 non-null  object
 15  Contract          594194 non-null  object
 16  PaperlessBilling  594194 non-null  object
 17  PaymentMethod     594194 non-null  object
 18  MonthlyCharges    594194 non-null  float64
 19  TotalCharges      594194 non-null  float64
 20  Churn             594194 non-null  object
dtypes: float64(2), int64(3), object(16)
memory usage: 95.2+ MB

In [25]:
train_df.describe()

,id,SeniorCitizen,tenure,MonthlyCharges,TotalCharges
count,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000
mean,297096.500000,0.114102,36.577258,65.866223,2494.377057
std,171529.177262,0.317936,25.061922,31.067444,2353.916710
min,0.000000,0.000000,1.000000,18.250000,18.800000
25%,148548.250000,0.000000,12.000000,29.900000,639.650000
50%,297096.500000,0.000000,35.000000,74.100000,1433.650000
75%,445644.750000,0.000000,62.000000,90.800000,4263.800000
max,594193.000000,1.000000,72.000000,118.750000,8684.800000

In [26]:
train_df_dummies = pd.get_dummies(train_df.drop(columns=['id', 'Churn']), drop_first=True)
train_df_target = train_df['Churn']
train_df_dummies.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,29,60.10,1653.85,True,True,True,True,False,False,...,False,False,False,False,True,False,True,False,False,True
1,0,58,69.50,3778.20,True,True,True,True,False,False,...,False,True,False,False,False,True,False,True,False,False
2,0,58,100.40,5841.35,True,True,False,True,False,True,...,False,True,False,True,False,False,True,False,True,False
3,0,1,69.70,70.70,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,True,False
4,0,1,70.45,70.45,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,True,False

In [27]:
train_df_dummies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 30 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   SeniorCitizen                          594194 non-null  int64
 1   tenure                                 594194 non-null  int64
 2   MonthlyCharges                         594194 non-null  float64
 3   TotalCharges                           594194 non-null  float64
 4   gender_Male                            594194 non-null  bool
 5   Partner_Yes                            594194 non-null  bool
 6   Dependents_Yes                         594194 non-null  bool
 7   PhoneService_Yes                       594194 non-null  bool
 8   MultipleLines_No phone service         594194 non-null  bool
 9   MultipleLines_Yes                      594194 non-null  bool
 10  InternetService_Fiber optic            594194 non-null  bool
 11  InternetService_No                     594194 non-null  bool
 12  OnlineSecurity_No internet service     594194 non-null  bool
 13  OnlineSecurity_Yes                     594194 non-null  bool
 14  OnlineBackup_No internet service       594194 non-null  bool
 15  OnlineBackup_Yes                       594194 non-null  bool
 16  DeviceProtection_No internet service   594194 non-null  bool
 17  DeviceProtection_Yes                   594194 non-null  bool
 18  TechSupport_No internet service        594194 non-null  bool
 19  TechSupport_Yes                        594194 non-null  bool
 20  StreamingTV_No internet service        594194 non-null  bool
 21  StreamingTV_Yes                        594194 non-null  bool
 22  StreamingMovies_No internet service    594194 non-null  bool
 23  StreamingMovies_Yes                    594194 non-null  bool
 24  Contract_One year                      594194 non-null  bool
 25  Contract_Two year                      594194 non-null  bool
 26  PaperlessBilling_Yes                   594194 non-null  bool
 27  PaymentMethod_Credit card (automatic)  594194 non-null  bool
 28  PaymentMethod_Electronic check         594194 non-null  bool
 29  PaymentMethod_Mailed check             594194 non-null  bool
dtypes: bool(26), float64(2), int64(2)
memory usage: 32.9 MB

In [28]:
train_df_dummies.describe()

       SeniorCitizen         tenure  MonthlyCharges   TotalCharges
count  594194.000000  594194.000000   594194.000000  594194.000000
mean        0.114102      36.577258       65.866223    2494.377057
std         0.317936      25.061922       31.067444    2353.916710
min         0.000000       1.000000       18.250000      18.800000
25%         0.000000      12.000000       29.900000     639.650000
50%         0.000000      35.000000       74.100000    1433.650000
75%         0.000000      62.000000       90.800000    4263.800000
max         1.000000      72.000000      118.750000    8684.800000

In [30]:
import scipy as sp
import sklearn as sk

hist_boosted = sk.ensemble.HistGradientBoostingClassifier()
hist_boosted.fit(train_df_dummies, train_df_target)

0.8612978252893836

In [31]:
hist_boosted.score(train_df_dummies, train_df_target)

0.8612978252893836

In [32]:
test_df = pd.read_csv('/kaggle/input/competitions/playground-series-s6e3/test.csv')
test_df.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,594194,Female,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,115.55,8061.50
1,594195,Female,0,Yes,No,71,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),19.80,1336.50
2,594196,Male,0,No,No,12,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),55.55,633.55
3,594197,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),84.10,6457.15
4,594198,Female,0,No,No,15,Yes,No,Fiber optic,Yes,No,No,No,Yes,Yes,Month-to-month,No,Electronic check,90.35,1233.65

In [33]:
predictions = hist_boosted.predict(test_df.drop(columns=['id']))
predictions[:10]

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- Contract
- Dependents
- DeviceProtection
- InternetService
- MultipleLines
- ...
Feature names seen at fit time, yet now missing:
- Contract_One year
- Contract_Two year
- Dependents_Yes
- DeviceProtection_No internet service
- DeviceProtection_Yes
- ...

In [34]:
# ============================================================================
# PRE-PROCESSING PIPELINE
# ============================================================================

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import warnings
warnings.filterwarnings('ignore')

# Step 1: Create a preprocessing function that handles categorical encoding consistently
def preprocess_data(df, is_training=True, encoder=None, scaler=None, target_col='Churn'):
    """
    Preprocess customer churn data with consistent encoding for train/test sets.
    
    Parameters:
    -----------
    df : pd.DataFrame
        Input dataframe
    is_training : bool
        Whether this is training data (True) or test data (False)
    encoder : dict
        Dictionary of encoders from training set (for test data)
    scaler : StandardScaler
        Fitted scaler from training set (for test data)
    target_col : str
        Name of target column (only in training data)
    
    Returns:
    --------
    X : pd.DataFrame
        Preprocessed features
    y : pd.Series (only if is_training=True)
        Target variable
    encoder : dict (only if is_training=True)
        Dictionary of encoders for reuse
    scaler : StandardScaler (only if is_training=True)
        Fitted scaler for reuse
    """
    
    df_processed = df.copy()
    
    # Identify feature columns (exclude id and target)
    feature_cols = [col for col in df_processed.columns if col not in ['id', target_col]]
    
    # Separate numeric and categorical features
    numeric_cols = df_processed[feature_cols].select_dtypes(include=[np.number]).columns.tolist()
    categorical_cols = df_processed[feature_cols].select_dtypes(include=['object']).columns.tolist()
    
    # Handle categorical variables with one-hot encoding
    if is_training:
        # For training data, fit the encoder
        df_dummies = pd.get_dummies(df_processed[categorical_cols], drop_first=True)
        encoder = {col: df_processed[col].unique() for col in categorical_cols}
    else:
        # For test data, ensure all categories match training data
        df_dummies = pd.get_dummies(df_processed[categorical_cols], drop_first=True)
    
    # Combine numeric and encoded categorical features
    X = pd.concat([df_processed[numeric_cols].reset_index(drop=True), 
                   df_dummies.reset_index(drop=True)], axis=1)
    
    # Handle missing values (fill with median for numeric, mode for categorical)
    if is_training:
        numeric_means = X[numeric_cols].mean()
        X[numeric_cols] = X[numeric_cols].fillna(numeric_means)
        # Fit and apply scaling
        scaler = StandardScaler()
        X[numeric_cols] = scaler.fit_transform(X[numeric_cols])
    else:
        # Use pre-computed statistics from training
        if numeric_cols:
            X[numeric_cols] = scaler.transform(X[numeric_cols])
    
    if is_training:
        # Extract target variable
        y = df_processed[target_col]
        return X, y, encoder, scaler
    else:
        return X, encoder, scaler


# Step 2: Apply preprocessing to training data
print("Preprocessing training data...")
X_train, y_train, encoder, scaler = preprocess_data(train_df, is_training=True)
print(f"Training data shape: {X_train.shape}")
print(f"Target distribution:\n{y_train.value_counts()}")
print(f"\nFeature columns: {X_train.columns.tolist()}")

Preprocessing training data...
Training data shape: (594194, 30)
Target distribution:
Churn
No     460377
Yes    133817
Name: count, dtype: int64

Feature columns: ['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges', 'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes', 'MultipleLines_No phone service', 'MultipleLines_Yes', 'InternetService_Fiber optic', 'InternetService_No', 'OnlineSecurity_No internet service', 'OnlineSecurity_Yes', 'OnlineBackup_No internet service', 'OnlineBackup_Yes', 'DeviceProtection_No internet service', 'DeviceProtection_Yes', 'TechSupport_No internet service', 'TechSupport_Yes', 'StreamingTV_No internet service', 'StreamingTV_Yes', 'StreamingMovies_No internet service', 'StreamingMovies_Yes', 'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes', 'PaymentMethod_Credit card (automatic)', 'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check']

In [35]:
# Step 3: Apply preprocessing to test data with same transformations
print("\nPreprocessing test data...")
X_test, _, _ = preprocess_data(test_df, is_training=False, encoder=encoder, scaler=scaler)
print(f"Test data shape: {X_test.shape}")

# Ensure test data has same columns as training data
missing_cols = set(X_train.columns) - set(X_test.columns)
extra_cols = set(X_test.columns) - set(X_train.columns)

if missing_cols:
    print(f"\nAdding missing columns from training: {missing_cols}")
    for col in missing_cols:
        X_test[col] = 0

if extra_cols:
    print(f"Removing extra columns not in training: {extra_cols}")
    X_test = X_test.drop(columns=extra_cols)

# Reorder test columns to match training
X_test = X_test[X_train.columns]
print(f"Final test data shape: {X_test.shape}")

Preprocessing test data...
Test data shape: (254655, 30)
Final test data shape: (254655, 30)

In [36]:
# Step 4: Retrain model on properly preprocessed data
print("\nRetraining model with preprocessed data...")
hist_boosted_v2 = sk.ensemble.HistGradientBoostingClassifier(random_state=42)
hist_boosted_v2.fit(X_train, y_train)

train_score = hist_boosted_v2.score(X_train, y_train)
print(f"Training accuracy: {train_score:.4f}")

# Make predictions on test data
predictions = hist_boosted_v2.predict(X_test)
predictions_proba = hist_boosted_v2.predict_proba(X_test)

print(f"\nPredictions shape: {predictions.shape}")
print(f"Predictions sample (first 10): {predictions[:10]}")
print(f"Prediction probabilities sample (first 5):\n{predictions_proba[:5]}")
print(f"\nChurn distribution in predictions: {np.unique(predictions, return_counts=True)}")

Retraining model with preprocessed data...
Training accuracy: 0.8614

Predictions shape: (254655,)
Predictions sample (first 10): ['No' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No']
Prediction probabilities sample (first 5):
[[0.94899654 0.05100346]
 [0.99867549 0.00132451]
 [0.89227577 0.10772423]
 [0.99664475 0.00335525]
 [0.48408489 0.51591511]]

Churn distribution in predictions: (array(['No', 'Yes'], dtype=object), array([205122,  49533]))

In [37]:
# Step 5: Create submission file
submission_df = pd.DataFrame({
    'id': test_df['id'],
    'Churn': predictions
})

# Save submission
submission_df.to_csv('submission.csv', index=False)
print("Submission file saved: submission.csv")
print(f"\nSubmission preview:\n{submission_df.head(10)}")

# ============================================================================
# PREPROCESSING PIPELINE SUMMARY
# ============================================================================
print("\n" + "="*70)
print("PREPROCESSING PIPELINE SUMMARY")
print("="*70)
print("""
The preprocessing pipeline includes the following steps:

1. DATA SEPARATION
   - Identifies numeric and categorical features
   - Separates target variable (Churn) from features
   - Excludes ID column from processing

2. CATEGORICAL ENCODING
   - One-hot encodes categorical variables
   - Uses drop_first=True to avoid multicollinearity
   - Ensures train/test columns match by adding missing columns

3. MISSING VALUE HANDLING
   - Fills numeric missing values with column mean
   - Properly handles categorical variables

4. FEATURE SCALING
   - Applies StandardScaler to numeric features
   - Ensures features are on similar scale (important for tree models)
   - Scaler is fitted on training data and applied to test data

5. SCHEMA ALIGNMENT
   - Reorders test columns to match training data
   - Adds missing columns with 0 values
   - Removes unexpected columns
   - Ensures feature consistency between train/test

INPUT: 
   - Training shape: {}, Target shape: {}
OUTPUT:
   - X_train shape: {}
   - X_test shape: {}
   - Number of features: {}

This pipeline ensures consistent preprocessing across train/test sets,
which is critical for accurate model performance on unseen data.
""".format(train_df.shape, y_train.shape, X_train.shape, X_test.shape, X_train.shape[1]))

Submission file saved: submission.csv

Submission preview:
       id Churn
0  594194    No
1  594195    No
2  594196    No
3  594197    No
4  594198   Yes
5  594199    No
6  594200   Yes
7  594201    No
8  594202    No
9  594203    No

======================================================================
PREPROCESSING PIPELINE SUMMARY
======================================================================

The preprocessing pipeline includes the following steps:

1. DATA SEPARATION
   - Identifies numeric and categorical features
   - Separates target variable (Churn) from features
   - Excludes ID column from processing

2. CATEGORICAL ENCODING
   - One-hot encodes categorical variables
   - Uses drop_first=True to avoid multicollinearity
   - Ensures train/test columns match by adding missing columns

3. MISSING VALUE HANDLING
   - Fills numeric missing values with column mean
   - Properly handles categorical variables

4. FEATURE SCALING
   - Applies StandardScaler to numeric features
   - Ensures features are on similar scale (important for tree models)
   - Scaler is fitted on training data and applied to test data

5. SCHEMA ALIGNMENT
   - Reorders test columns to match training data
   - Adds missing columns with 0 values
   - Removes unexpected columns
   - Ensures feature consistency between train/test

INPUT:
   - Training shape: (594194, 21), Target shape: (594194,)
OUTPUT:
   - X_train shape: (594194, 30)
   - X_test shape: (254655, 30)
   - Number of features: 30

This pipeline ensures consistent preprocessing across train/test sets,
which is critical for accurate model performance on unseen data.